name: Notify Release

on:
  release:
    types:
      - created
      - published


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Notify Slack on Release
        uses: instantish/notify-slack-on-release@1.0.0
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}